import type { Metadata } from "next";
import { Noto_Kufi_Arabic  } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import WhatsAppButton from "@/components/ui/WhatsAppButton";

// const raleway = Raleway({
//   subsets: ["latin"],
//   weight: ["400", "700"], 
//   display: "swap",
// });
export const notoKufiArabic = Noto_Kufi_Arabic({
  subsets: ['arabic'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
  variable: '--font-noto-kufi'
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={notoKufiArabic.className}
      >
        <Header />

        {children}
        <WhatsAppButton/>
      </body>
    </html>
  );
}
